window.tpl = ['<div>',
    '<div class=weui-panel style="margin-top:-1px;">',
        '<div class="weui-panel_bd app-head" style="background: url(https://biz.cli.im<%=data.list.item.background%>) 50% 0 / cover;">',
            '<div class="weui-media-box weui-media-box_appmsg">',
                '<div class="weui-media-box__hd face"> <img class="weui-media-box__thumb" src="<%=data.list.item.face%>" alt="">',
                '</div>',
                '<div class="">',
                    '<h5 class="weui-media-box__title">',
                        '<%=data.list.item.name%>',
                    '</h5>',
                    '<p class>',
                        '<%=data.list.item.position%>',
                    '</p>',
                    '<p class>',
                        '<%=data.list.item.orgname%>',
                    '</p>',
                '</div>',
            '</div>',
        '</div>',
    '</div>',
    '<div class=weui-cells>',
        '<%if(data.list.item.worktel) {%>',
            '<a class=weui-cell href=tel:<%=data.list.item.worktel%>>',
                '<div class="weui-cell-bd weui-label biz_vcard_cell_title">',
                    '<p>固定电话</p>',
                '</div>',
                '<div class=><%=data.list.item.worktel%></div>',
            '</a>',
        '<%}%>',
        '<%if(data.list.item.mobiletel) {%>',
            '<a class=weui-cell href=tel:<%=data.list.item.mobiletel%>>',
            '<div class="weui-cell-bd weui-label biz_vcard_cell_title">',
                '<p>移动电话</p>',
            '</div>',
            '<div class=><%=data.list.item.mobiletel%></div>',
            '</a>',
        '<%}%>',
        '<%if(data.list.item.workfax) {%>',
            '<a class=weui-cell>',
                '<div class="weui-cell-bd weui-label">',
                    '<p>',
                        '传真',
                    '</p>',
                '</div>',
                '<div class=>',
                    '<%=data.list.item.workfax%>',
                '</div>',
            '</a>',
        '<%}%>',
        '<%if(data.list.item.email) {%>',
            '<a class=weui-cell href=mailto:<%=data.list.item.email%>>',
                '<div class="weui-cell-bd weui-label">',
                    '<p>电子邮箱</p>',
                '</div>',
                '<div class=><%=data.list.item.email%></div>',
            '</a>',
        '<%}%>',
    '</div>',
'',
    '<div class=weui-cells>',
        '<%if(data.list.item.email) {%>',
            '<a class=weui-cell href=<%=data.list.item.url%>>',
                '<div class="weui-cell-bd weui-label">',
                    '<p>主页网址</p>',
                '</div>',
                '<div class=><%=data.list.item.url%></div>',
            '</a>',
            '<%}%>',
                        '<%if(data.list.item.weibo) {%>',
                            '<a class=weui-cell href=<%=data.list.item.weibo%>>',
                                '<div class="weui-cell-bd weui-label">',
                                    '<p>',
                                        '微博网址',
                                    '</p>',
                                '</div>',
                                '<div class=>',
                                    '<%=data.list.item.weibo%>',
                                '</div>',
                            '</a>',
                            '<%}%>',
'',
                                '<%if(data.list.item.weibo) {%>',
                                    '<div class=weui-cell>',
                                        '<div class="weui-cell-bd weui-label">',
                                            '<p>微信号</p>',
                                        '</div>',
                                        '<div class=>',
                                            '<div class=>',
                                                '<%=data.list.item.weixin%>',
                                            '</div>',
                                        '</div>',
                                    '</div>',
                                    '<%}%>',
'',
    '</div>',
'',
'',
    '<div  class=weui-cells>',
        '<div class=weui-cell v-show="list.item.baidumap_link || list.item.workadr">',
            '<div class="weui-cell_bd weui-label biz_vcard_cell_title">',
                '<p>',
                    '地址',
                '</p>',
            '</div>',
            '<div class="weui-cell_bd weui-cell_primary" <%if(data.list.item.baidumap_link){%>style="padding-right:50px;"<%}%>">',
                '<%=data.list.item.workadr%>',
                '<%if(data.list.item.baidumap_link){%>',
                    '<a href=https://biz.cli.im<%=data.list.item.baidumap_link%> class="weui-btn weui-btn-mini weui-btn_default app-btn-right">地图</a>',
                '<%}%>',
            '</div>',
        '</div>',
    '</div>',
'',
    '<%if(data.list.item.note) {%>',
        '<div class=weui-cells>',
            '<div class=weui-cell>',
                '<div class="weui-cell-bd weui-label">',
                    '<p class=overtext>个人说明</p>',
                '</div>',
                '<div class="weui-cell-bd weui-cell-primary">',
                    '<span class=biz_vcard_note><%=data.list.item.note%></span>',
                '</div>',
            '</div>',
        '</div>',
        '<%}%>',
'</div>',
'<div class="app-bottom">',
    '<div class="app-bottom-btn-wrap">',
    '<a class="weui-btn weui-btn_primary download-card" href="<%=data.list.item.download_href%>" class="bottom_vacrd_link">保存到通讯录</a>',
    '</div>',
'</div>',

'<div class="qrcode-dialog" style="display:none;">',
    '<div class="weui-mask"></div>',
    '<div class="weui-dialog" style="background: transparent; text-align:center">',
        '<div class="weui-dialog__bd">',
            '<div id="qr" class="qr-img"></div>',
            '<p>长按二维码， 选择识别图中二维码</p>',
            '<a href="javascript:;" class="close-qrcode-dialog"><i class="weui-icon-cancel"></i></a>',
        '</div>',
    '</div>',
'</div>',
].join('');


var data = {
    "edition_id": "1",
    "user_account": "liangweiliang@yunba.io",
    "qrcode_img": "\/\/qr.api.cli.im\/qr?data=http%3A%2F%2Fqr10.cn%2FM14kIJ&level=H&transparent=&bgcolor=%23ffffff&forecolor=%23000000&blockpixel=12&marginblock=1&logourl=&size=120&kid=bizcliim&time=1476203753&key=4b87db052fdac1cf8fcdfc84a0cd725f",
    "is_valid": 1,
    "user_id": "1613237",
    "title": "William \u7684\u540d\u7247",
    "block": {
        "id": "1452852",
        "coding": "M14kIJ",
        "qrcode_img": "\/\/qr.api.cli.im\/qr?data=http%3A%2F%2Fqr10.cn%2FM14kIJ&level=H&transparent=&bgcolor=%23ffffff&forecolor=%23000000&blockpixel=12&marginblock=1&logourl=&size=120&kid=bizcliim&time=1476203753&key=4b87db052fdac1cf8fcdfc84a0cd725f",
        "lang": "cn",
        "face": "\/\/bizimg.clewm.net\/408\/312\/1312408\/1476201115911464970f2bdace916b95a0d645331b0d31476200183.jpg@100Q",
        "background": "\/Public\/images\/vcardbg7.jpg",
        "name": "William",
        "orgname": "\u4eba\u7c7b\u793e\u4f1a",
        "depname": "",
        "layout": "0",
        "position": "\u8bd7\u4eba, \u54f2\u5b66\u5bb6\uff0c\u7269\u7406\u5b66\u5bb6",
        "mobiletel": "13725702893",
        "worktel": "13725702893",
        "workfax": "13725702893",
        "workadr": "\u5e7f\u4e1c\u7701\u6df1\u5733\u5e02\u798f\u7530\u533a\u798f\u4e2d\u4e09\u8def",
        "email": "superbill2012@qq.com",
        "url": "http:\/\/google.com",
        "url2": "",
        "sucai_id": "0",
        "biz_coding_id": "",
        "is_biz": "0",
        "tpl_skin": "newphone,af23027",
        "tpl_attr": "",
        "weibo": "http:\/\/weibo.com\/1655366740",
        "weixin": "liang_weiliang",
        "weixin_link": "",
        "msn": "",
        "qq": "753154306",
        "qq_link": "",
        "note": "\u4e2a\u4eba\u8bf4\u660e\u8bf4\u660e\u3002\u3002\u3002",
        "color": "",
        "custom_content": "N;",
        "is_stop": "0",
        "is_del": "0",
        "is_dimission": "0",
        "addtime": "2016-10-11 23:51:55",
        "lasttime": "1476203749",
        "user_id": "1613237",
        "cooper_id": "0",
        "tpl_id": "0",
        "cls_id": "409040",
        "sort": "0",
        "coordinates_lat": "22.548991",
        "coordinates_lng": "114.069968",
        "open_id": "0",
        "enter_url": "\/\/qr10.cn\/M14kIJ"
    },
    "sucai_id": "0",
    "tpl_code": "newphone",
    "tpl_code_skin": "af23027",
    "is_expire": 0,
    "tree_list": [{
        "qrcode_img": "\/\/qr.api.cli.im\/qr?data=http%3A%2F%2Fqr10.cn%2FM14kIJ&level=H&transparent=&bgcolor=%23ffffff&forecolor=%23000000&blockpixel=12&marginblock=1&logourl=&size=120&kid=bizcliim&time=1476203753&key=4b87db052fdac1cf8fcdfc84a0cd725f",
        "module": "vcard_biz",
        "module_icon": "",
        "is_unfold": "1",
        "is_stop": "0",
        "item": {
            "id": "1452852",
            "coding": "M14kIJ",
            "qrcode_img": "\/\/qr.api.cli.im\/qr?data=http%3A%2F%2Fqr10.cn%2FM14kIJ&level=H&transparent=&bgcolor=%23ffffff&forecolor=%23000000&blockpixel=12&marginblock=1&logourl=&size=120&kid=bizcliim&time=1476203753&key=4b87db052fdac1cf8fcdfc84a0cd725f",
            "lang": "cn",
            "face": "\/\/bizimg.clewm.net\/408\/312\/1312408\/1476201115911464970f2bdace916b95a0d645331b0d31476200183.jpg@100Q",
            "background": "\/Public\/images\/vcardbg7.jpg",
            "name": "William",
            "orgname": "\u4eba\u7c7b\u793e\u4f1a",
            "depname": "",
            "layout": "0",
            "position": "\u8bd7\u4eba, \u54f2\u5b66\u5bb6\uff0c\u7269\u7406\u5b66\u5bb6",
            "mobiletel": "13725702893",
            "worktel": "13725702893",
            "workfax": "13725702893",
            "workadr": "\u5e7f\u4e1c\u7701\u6df1\u5733\u5e02\u798f\u7530\u533a\u798f\u4e2d\u4e09\u8def",
            "email": "superbill2012@qq.com",
            "url": "http:\/\/google.com",
            "url2": "",
            "sucai_id": "0",
            "biz_coding_id": "",
            "is_biz": "0",
            "tpl_attr": "",
            "weibo": "http:\/\/weibo.com\/1655366740",
            "weixin": "liang_weiliang",
            "weixin_link": "",
            "msn": "",
            "qq": "753154306",
            "qq_link": "",
            "note": "\u4e2a\u4eba\u8bf4\u660e\u8bf4\u660e\u3002\u3002\u3002",
            "color": "",
            "custom_content": "N;",
            "is_stop": "0",
            "is_del": "0",
            "is_dimission": "0",
            "addtime": "2016-10-11 23:51:55",
            "lasttime": "1476203749",
            "user_id": "1613237",
            "cooper_id": "0",
            "tpl_id": "0",
            "cls_id": "409040",
            "sort": "0",
            "coordinates_lat": "22.548991",
            "coordinates_lng": "114.069968",
            "open_id": "0",
            "enter_url": "\/\/qr10.cn\/M14kIJ",
            "title": null,
            "vcard_language": {
                "cn": {
                    "name": "\u59d3\u540d",
                    "face": "\u5934\u50cf",
                    "nickname": "\u6635\u79f0",
                    "mobiletel": "\u79fb\u52a8\u7535\u8bdd",
                    "worktel": "\u56fa\u5b9a\u7535\u8bdd",
                    "workfax": "\u4f20\u771f",
                    "email": "\u7535\u5b50\u90ae\u7bb1",
                    "position": "\u804c\u4f4d",
                    "orgname": "\u516c\u53f8\u540d\u79f0",
                    "depname": "\u90e8\u95e8",
                    "workadr": "\u5730\u5740",
                    "url": "\u4e3b\u9875\u7f51\u5740",
                    "weibo": "\u5fae\u535a\u7f51\u5740",
                    "weixin": "\u5fae\u4fe1\u53f7",
                    "qq": "QQ\u53f7",
                    "msn": "MSN",
                    "note": "\u4e2a\u4eba\u8bf4\u660e",
                    "save": "\u4fdd\u5b58\u5230\u901a\u8baf\u5f55",
                    "qrcode": "\u4e8c\u7ef4\u7801",
                    "highsave": "\u9ad8\u7ea7\u4fdd\u5b58",
                    "wxshare": "\u5206\u4eab",
                    "wxfav": "\u6536\u85cf"
                },
                "en": {
                    "name": "Name",
                    "face": "Face",
                    "nickname": "Nickname",
                    "mobiletel": "Mobile",
                    "worktel": "Telephone",
                    "workfax": "Fax",
                    "email": "Email",
                    "position": "Position",
                    "orgname": "ORG",
                    "depname": "Department",
                    "workadr": "Address",
                    "homeadr": "Address",
                    "url": "URL",
                    "weibo": "Weibo",
                    "weixin": "Wechat",
                    "msn": "MSN",
                    "qq": "QQ",
                    "note": "Description",
                    "save": "Save to Contact",
                    "qrcode": "QR Code",
                    "highsave": "Senior save",
                    "wxshare": "Share",
                    "wxfav": "Add to Favorites"
                }
            },
            "download_href": "\/\/biz.cli.im\/link\/?b=weixin&utitle&type=vcard&url=%2F%2Fbiz.cli.im%2Fvcard%2Fd%3Fid%3DM14kIJ&lang=cn",
            "ext_data": {
                "basic_more": null,
                "email": null,
                "tel": null,
                "message": null,
                "address": null,
                "url": null,
                "fax": null
            },
            "baidumap_link": "\/site\/map\/?id=M14kIJ&lng=114.069968&lat=22.548991&type=vcard",
            "baidumap_img": "\/\/api.map.baidu.com\/staticimage?center=114.069968,22.548991&width=500&height=400&zoom=14&markers=114.069968,22.548991",
            "background_color": "f23027"
        }
    }],
    "tongji": {
        "token_user_id": "1312408",
        "main": {
            "coding": "M14kIJ",
            "name": "William \u7684\u540d\u7247"
        }
    }
};
var open_id = "";
var is_android = "" || false;
var is_weixin = "" || false;

var appData = {
    list: data.tree_list[0]
}



var App = Backbone.View.extend({
  events: {
    "click .download-card":          "showQrcode",
    'click .close-qrcode-dialog': 'hideQrcode'
  },
  showQrcode: function() {
    this.$('.qrcode-dialog').show();
    return false;
  },
  hideQrcode: function() {
    this.$('.qrcode-dialog').hide();
  },

  initialize: function() {
    this.data = appData;
  },
  template: _.template(tpl, {'variable': 'data'}),
  render: function() {
    this.$el.html(this.template(this.data));
    this.$el.find('#qr').qrcode({
        render: 'image',
        text: this.getCartQrcode()
    });
    return this;
  },
  getCartQrcode: function() {
    var data = this.data;
    var cardText =['data=BEGIN:VCARD',
    'FN:' + data.list.item.name,
    'ORG:' + data.list.item.orgname,
    'ADR;TYPE=WORK:;;'+ data.list.item.workadr,
    'TITLE:' + data.list.item.position,
    'TEL;CELL:' + data.list.item.worktel,
    'TEL;CELL:' + data.list.item.mobiletel,
    'URL:' + data.list.item.url,
    'EMAIL;TYPE=PREF,INTERNET:' + data.list.item.email,
    'END:VCARD']
        .join('\n');
    return cardText;
  }

});

$(function() {
    var app = window.app = new App();
    $('#app').append(app.render().$el);
});